# Generated by Django 4.0 on 2021-12-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essbeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sub_head',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
