# Generated by Django 4.0 on 2021-12-30 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essbeeapp', '0004_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone must be in the format: '+999999999'.Please enter 10 digits mobile number.", regex='^\\+?1?\\d{10,10}$')])),
                ('website', models.CharField(max_length=100)),
            ],
        ),
    ]
