# Generated by Django 4.0 on 2021-12-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essbeeapp', '0006_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='clients_logo/')),
            ],
        ),
    ]
