# Generated by Django 4.0 on 2021-12-31 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essbeeapp', '0009_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_comment',
            name='blog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='essbeeapp.blog'),
            preserve_default=False,
        ),
    ]
