# Generated by Django 4.0 on 2021-12-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essbeeapp', '0010_blog_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blog_comment',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
